// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wldvlkzqwcgoykdnoinm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsZHZsa3pxd2Nnb3lrZG5vaW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzA0MDEsImV4cCI6MjA2MzY0NjQwMX0.FCzxdS3oGOIS517BTJQPjoZONnClIIxG_iXAYPNVERE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);